### ISSUE TITLE
Stricter typing for widget inputs

### ISSUE THREAD

**Issue by nathan-yung-sdx** [sdxmessaging/ui-widgets#112]
We have many type casting for the attrs passed into components like 
```typescript
as IOptionField
```

- [x] Pass a generic `T` type into `IPropWidget` & `IFileWidget` so that the attributes can be inferred.
- [x] Add template literal strings as type for `FieldType` so that a primitive string type is no longer needed, it will enhance the field type inference

**Comment by andy-barlow** [comment]
Reviewed and closed
