### ISSUE TITLE
Enable top label for toggle inputs

### ISSUE THREAD

**Issue by sdx-crispin** [sdxmessaging/ui-widgets#137]
What it says in the title....

**Comment by MichaelPastuch** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakM3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--21610eef47dc7bb7a9b886f4791805259336e904/CleanShot%202023-09-20%20at%2013.37.46.png)

Setting the `layout` to `floatAlways` will replace the inline label with a typical label as seen on text widgets.
