### ISSUE TITLE
CheckList - Theme List Entries

### ISSUE THREAD

**Issue by MichaelPastuch** [sdxmessaging/ui-widgets#149]
Create theme options for CheckList option rows:

* SingleOption
* SingleOptionSelected
* MultiOption
* MultiOptionSelected

Only show checkboxes for option rows when `multiple` is true

**Comment by SDX-Kathryn** [comment]
<img width="898" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTVRQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46dc79f4879a393265e0316a6e24e60e1af1abc1/Single-multi%20select.png" alt="Single-multi select.png" />

**Comment by SDX-Kathryn** [comment]
### **Dropdown list example**
XD link:
https://xd.adobe.com/view/cd9f9986-998b-49d8-ba0b-56780162d820-98cc/

**Comment by MichaelPastuch** [comment]
Auto close selection list when an item is selected in "single select" mode.
