### ISSUE TITLE
Reconciliation Report - Breakpoints

### ISSUE THREAD

**Issue by SDX-Kathryn** [sdxmessaging/ui-widgets#156]
Build currently based on landscape tablet.

@SDX-Kathryn UI design 
- [x] Portrait tablet
- [x] Landscape Tablet
- [x] Desktop

Implement
- [ ] Review breakpoints - @SDX-Kathryn  @sdx-joe @sdx-ollie 

Excel mockup:

[Agent and Round reconciliation.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXpnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--373d148e80e23c6413688e51799ca4b51cea959f/Agent%20and%20Round%20reconciliation.xlsx)

**Comment by andy-barlow** [comment]
<img width="408" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXZnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45fe5b9c1523fbbbf1d1385d23e23129f50a3f83/CleanShot%202024-03-14%20at%2017.19.29.png" alt="CleanShot 2024-03-14 at 17.19.29.png" />

**Comment by SDX-Kathryn** [comment]
### **Portrait Tablet v.4** 

XD link w. annotations:
https://xd.adobe.com/view/354e10f0-73fd-4ad8-8e99-7450ebb23781-601d/

XD link:
https://xd.adobe.com/view/8eada0a7-0ece-450b-9b2e-5726f83c7299-dbfe/

**Comment by SDX-Kathryn** [comment]
### **Landscape Tablet v.4**

XD link w. annotations:
https://xd.adobe.com/view/f9909340-4bdc-4cb4-981e-f05b8abc343c-acc3/

XD link:
https://xd.adobe.com/view/f5ce71e4-a483-438b-aa31-7e1b6b5cb7e4-a09d/

**Comment by SDX-Kathryn** [comment]
### **Landscape Tablet v.4**

<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzRhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e77ff0cc9ef6fc5785740090175fad56f4ebc0d/Reconciliation%20LT%20demo.gif" alt="Reconciliation LT demo.gif" />

**Comment by SDX-Kathryn** [comment]
Final calculation spreadsheet:
[Agent and Round reconciliation spreadsheet v.2 - Final .xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0FhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97ce9a7df9d8a8a0b4b84bb71552196984f166a4/Agent%20and%20Round%20reconciliation%20spreadsheet%20v.2%20-%20Final%20.xlsx)
