### ISSUE TITLE
File/Image Input Delete Pending File

### ISSUE THREAD

**Issue by MichaelPastuch** [sdxmessaging/ui-widgets#35]
We can easily remove files from the FileMulti and ImageMulti components, but no such option is present for their singular variants Add a "delete" button to the FileSelect and ImageSelect components with similar behaviour to the multi variants.

**Comment by danrainesdx** [comment]
I've pushed a change with a small x in the corner of the file upload box for removing pending file

**Comment by MichaelPastuch** [comment]
The remove icon looks good, but I think it is on the display components instead of their respective input versions. Could we move the remove button to the `FileSelect` and `ImageSelect` components?

**Comment by danrainesdx** [comment]
I have moved the remove button to the FileSelect & ImageSelect components and added an ImageSelect viewer to the examples page.

**Comment by MichaelPastuch** [comment]
Looks great, this missing functionality is in high demand for at least one project we're working on.

I've made a couple minor changes to the styling of the remove buttons:
 * File input is now using a flexbox to help position and center align button
 * Image input is now using absolute position to place the button. Wide images pushed button to the bottom, while narrow images left the button at the top
 * The buttons now use the "navClass" theme for colour instead of a fixed red
