### ISSUE TITLE
Checkbox/Toggle Conditional Label

### ISSUE THREAD

**Issue by MichaelPastuch** [sdxmessaging/ui-widgets#36]
Add support an extra label on the right side of the icon displaying a label based on the value. The conditional labels could be passed to the component by changing the field config to an `IOptionField` where we could define the labels for true/false values:

```typescript
m(ToggleInput, {
  // id, label, etc...
  options: [
    { label: "On", value: true },
    { label: "Off", value: false }
  ]
})
```

The option labels will be an empty array by default. The component should support one or both option labels if present.

**Comment by MichaelPastuch** [comment]
The appropriate label should be shown when the toggle value matches in a manner that matches the `onText` or `offText` in Fluent UI:
https://developer.microsoft.com/en-us/fluentui#/controls/web/toggle

**Comment by MichaelPastuch** [comment]
I reviewed the toggle labels, looking solid. I've removed the bold text, and noticed that we can filter the given options to find our label (if provided) before building the mithril elements. The display variant of the toggle component should be to also reflect these labels.

It's probably not an issue at the moment, but the toggle input does not currently "wrap" a checkbox (clipped out of view). The stream values work as expected, but if we build a FormData out of a containing form, no values will be set from this widget as there is no input element on the DOM.

**Comment by danrainesdx** [comment]
Do we want to implement a wrapped checkbox so that this issue is resolved?

**Comment by MichaelPastuch** [comment]
I've merged the checkbox and toggle components, both now contain a clipped checkbox element and support labels based on their value. Their icons are set as protected properties in the base Checkbox class, and are overriden in the derived  Toggle class.
