### ISSUE TITLE
Show/Hide Password Toggle

### ISSUE THREAD

**Issue by MichaelPastuch** [sdxmessaging/ui-widgets#38]
The current PasswordInput component has a show/hide checkbox inline with the input label, which toggles the input type. While functional, it looks a bit dated.

Move the toggle button into the text input region and present as an "eye" icon ("fa-eye" and "fa-eye-slash"). The CurrencyInput component melp help as it displays the currency unit inline with the text input via CSS flexbox.

**Comment by danrainesdx** [comment]
Implemented and pushed - also added a "password strength" chunk of code to determine the strength of the password being typed. Discussed in the meeting that it could be worth making that a component in and of itself that can be easily plugged in.

**Comment by MichaelPastuch** [comment]
I've reviewed the password component improvements and slightlty tweaked the component layout to closer match the currency input (different input text colours and borders play nicer with the currency input).

I've moved static password scoring and checking functions outside of the class, they can be safely added to the file's "global scope" as out build process will keep everything tidy.

The password score itself has been slightly refactored to have it's stream value mapped from the given input value. This pattern should work well id we make a dedicated password strength component in future.

**Comment by danrainesdx** [comment]
Great, thanks Michael 👍

**Comment by MichaelPastuch** [comment]
Measuring password strength is a pretty tricky one. Quite a few of the 10 most popular passwords from the Adobe stolen passwords list are considered "average" strength via our conditions, we may benefit from researching into other libraries out there for that metric.
