### ISSUE TITLE
Enhanced DOB input

### ISSUE THREAD

**Issue by andy-barlow** [sdxmessaging/ui-widgets#53]
During the demos we did at the CCA Conference it became clear, especially using a mobile, that we could do better in terms of supporting the entry of DOB, in particular we should automatically advance on completion of the constituent day, month and year elements.

As most people know their DOB, we don't need to worry about validation, other than the maximum and minimum days and months.

- [x] enforce two digit entry of day, valid entries 01 to 31
- [x] enforce two digital entry of month, valid entries 01 to 12
- [x] enforce four digit entry of year
- [x] automatically advance from day and month as they are completed
- [x] support for [2-digit]/[2-digit]/[4-digit] fields, with validation as above

**Comment by MichaelPastuch** [comment]
Validation state should be set on the inputs if the "whole date" fails creation (eg. 29/02/2023 input passes each part validation, but produces an invalid date).

[Further reading on MDN](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation)

**Comment by nathan-yung-sdx** [comment]
> Validation state should be set on the inputs if the "whole date" fails creation (eg. 29/02/2023 input passes each part validation, but produces an invalid date).
> 
> [Further reading on MDN](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation)

Ui-widgets date input now correctly validates the whole date including February leap year dates
