### ISSUE TITLE
Enhance Value Validation

### ISSUE THREAD

**Issue by MichaelPastuch** [sdxmessaging/ui-widgets#67]
`src/validation.ts` contains methods for further validating widget values with respect to their field. We currently only enforce the required attribute but should expand it to cover more field validation options.

- [x] `type` could be enforced for the likes of "phone" or "email", browsers validate these fields on form submit, can we access their validation methods?
- [x] `max` and `min` for numeric types (number, range) if present
- [x] `maxlength` and `minlength` for "string" types (anything but numbers, dates, color)
- [x] `pattern` for "string" types.
- [x] `inputmode` will be subject to the widget type
- [ ] `accept` should already be enforced quite well by the file input, but could be worth exploring where several file inputs with different accept values are tied to a single file list stream.
- [x] Create a base class component which combines results from the HTML input element (`checkValidity`) and our validation function on the value stream. The input won't be available until at least after the first draw, can we call a validation helper function in the `onupdate` function and redraw if the value has changed?
- [x] Update `BaseInput` and `TextArea` classes to extend the and use validation base class component
- [x] Create an extended version of `IPropWidget` for layout components, that accepts a validity flag
- [x] Pass results from validation check to the updated layout components, this will warrant minor refactors to the majority of input components. Date and CardDate widgets should already have their own validity flag that can be passed to the layout component.

The validation function is primarily used to determine whether the widget should show the `invalidInputWrapper` class, and is not a replacement for the browser provided validation. The class changes can provide fast feedback, as opposed to the browser validation that is typically highlighted when the form is submitted.

**Comment by ted-while** [comment]
`public onupdate({ dom }: CVnodeDOM<IPropWidget>) {
		const input = dom.querySelector("input") as HTMLInputElement;
		if (input) {
			console.log(input.id, input.checkValidity());
		}
	}`
