### ISSUE TITLE
Select Dropdown onfocus vs onclick

### ISSUE THREAD

**Issue by nathan-yung-sdx** [sdxmessaging/ui-widgets#73]
When clicking on the LABEL of the input when the input is a dropdown selection menu, the field would get "focused" instead of dropping down. Clicking on the label should directly show the dropdown box instead of only focusing on it.

**Comment by ted-while** [comment]
this might not be possible without some nasty fudge. currently the behaviour we want is default on mobile but not on desktop as the discussion here details https://www.sitepoint.com/community/t/how-to-tie-the-label-to-a-dropdown-menu/43204/4

**Comment by nathan-yung-sdx** [comment]
Native browsers' select does not allow being opened programmatically. This cannot be resolved unless we make a custom dropdown widget, which is not a priority at the moment.

**Comment by nathan-yung-sdx** [comment]
Issue fixed with latest commit, made select a fixed float label & added a "placeholder" for default select that has no value.
