### ISSUE TITLE
 Add a browser native date select component next to the date input

### ISSUE THREAD

**Issue by nathan-yung-sdx** [sdxmessaging/ui-widgets#76]
Even though we decided to keep our 3-input date because of the intuitiveness (more so than Material UI), we can still enhance our current dateInput.

We should do something similar like [Material UI](https://mui.com/components/pickers/). Have a date picker button next to our date input. Making a custom Calendar dropdown might be time-consuming & tricky, but it is still doable. Check image at the bottom for reference.

However, look into ways to put browser native date component first, then we can decide whether to build our own or use browser native picker. 

I've found something that might work: setting css `input::-webkit-datetime-edit` to display none could hide the browser native date input but keep the calendar icon (might be subject to browser types), or maybe use queryselector for the id `date-time-edit` to hide it (also might be subject to browser types). So far on Chrome, the id seems to be the same for multiple date inputs.

<img width="328" alt="Screenshot 2021-11-15 at 09 22 06" src="https://user-images.githubusercontent.com/85952006/141755703-81869604-59cb-4483-a178-304479503c9d.png">

**Comment by nathan-yung-sdx** [comment]
After a little research & experiment, it is very inconsistent across browsers (e.g. Chrome has a calendar button whereas firefox doesn't). Plus, browsers for desktop web pages do not allow programmatically invoke a show on the calendar. It has to be clicked on a visible input, so hiding the edit input does not work on some browsers other than Chrome.

Our best bet is to make a custom date picker but that would not be prioritised at the moment (It's only a nice-to-have).

**Comment by MichaelPastuch** [comment]
Fulfilled by sdx-engage#108
